# All Car Data
# Longitudinal

# Put the gain values

time stamp
float32 x
float32 y
#float32 x_velocity
#float32 y_velocity
float32 current_velocity
float32 desired_velocity
float32 desired_acceleration
int64 throttle_command
int64 brake_command

# Lateral

#float32[][] waypoints
#float32multiarray ahead_waypoints
float32 heading
float32 yaw_rate
float32 lateral_error
float32 heading_error
float32 yaw_rate_error
float32 feedforward_angle
float32 feedback_angle
float32 total_angle
float32 steering_command

